# Generated by Django 4.2.5 on 2023-10-18 01:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webbot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="EAN",
            new_name="ean",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="MPN",
            new_name="mpn",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="SKU",
            new_name="sku",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="UPC",
            new_name="upc",
        ),
    ]
